---
- name: Add ppa brightness
  apt_repository:
      repo: 'ppa:apandada1/brightness-controller'
      state: present

- name: Install brightness
  apt:
    name: brightness-controller

- name: Add ppa Mainline
  apt_repository:
      repo: 'ppa:cappelikan/ppa'
      state: present

- name: Install Mainline
  apt:
    name: mainline