---
home_controller: "{{ lookup('env', 'HOME') }}"
home_host: "{{ ansible_env.HOME  }}"
ansible_python_interpreter: "/usr/bin/python"
#ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
# ansible_become_method: sudo