---
- name: Install some packages
  apt:
      name: "{{ items }}"
      state: latest
  vars:
      items:
      - filezilla
      - traceroute
      - flameshot
      - nmap
      - sssd
      - lightdm
      - firefox
      - vim
      - whois
      - curl
      - net-tools
      - openvpn
      - network-manager-openvpn
      - network-manager-openvpn-gnome
    
- name: Download Google Chrome
  shell: wget http://192.168.8.54/linux/google-chrome-stable_current_amd64.deb -P /tmp
  
- name: Install Google Chrome
  shell: sudo apt install /tmp/./google-chrome-stable_current_amd64.deb -y

- name: Download Slack
  shell: wget http://192.168.8.54/linux/slack-desktop-4.4.3-amd64.deb -P /tmp

- name: Install Slack
  shell: sudo apt install /tmp/./slack-desktop-4.4.3-amd64.deb -y

- name: Install TeamViewer dependencies
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - libjpeg62
    - libxinerama1
    - libxrandr2
    - libxtst6

- name: Download TeamViewer
  shell: wget http://192.168.8.54/linux/teamviewer_amd64.deb -P /tmp

- name: Install TeamViewer
  shell: sudo apt install /tmp/./teamviewer_amd64.deb -y

- name: Download Slack
  shell: wget http://192.168.8.54/linux/slack-desktop-4.4.3-amd64.deb -P /tmp

- name: Install Slack
  shell: sudo apt install /tmp/./slack-desktop-4.4.3-amd64.deb -y

- name: Auto remove 
  shell: sudo apt-get autoremove -y

- name: Download zoiper
  get_url:
    url: http://192.168.8.54/linux/Zoiper_3.3_Linux_Free_32Bit_64Bit.tar.gz
    dest: "{{ home_host }}"

- name: Extract zoiper files
  unarchive:
    src: "{{ home_host }}/Zoiper_3.3_Linux_Free_32Bit_64Bit.tar.gz"
    dest: "{{ home_host }}"
    remote_src: yes
    
- name: install zoiper
  expect:
    command: "./Zoiper_3.3_Linux_Free_64Bit.run"
    responses: 
      'Press \[Enter\] to continue :': "\n"
      'Do you accept this license\? \[y\/n\]:': "y"
      'Add Desktop Shortcut \[Y\/n\] :': "Y"
      'Is the selection above correct\? \[Y\/n\]:': "Y"
      'Installation Directory \[\/usr\/share\/Zoiper\]:': "\/usr\/share\/Zoiper"
      'Do you want to continue\? \[Y\/n\]:': "Y"
      'Launch Zoiper  \[Y\/n\]:': "Y"
    chdir: "{{ home_host }}"
    echo: yes

#==========Install dbeaver==============
- name: Install openjdk-8
  apt:
    name: openjdk-8-jdk
    
- name: Add apt key
  shell: wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | apt-key add -

- name: Add the repository to source list
  shell: echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list

- name: Install dbeaver
  apt: 
    name: dbeaver-ce
    update-cache: yes
    
- name: Add apt key
  shell: wget -O - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -

- name: Add the repository to source list
  shell: echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

- name: Install sublime-text
  apt: 
    name: sublime-text
    update-cache: yes
    
- name: Remove ubuntu-web-launcher -> to remove amazon launcher
  apt:
    name: ubuntu-web-launchers
    purge: yes
    state: absent


