---
- name: Install Auto Upgrade Ubuntu
  apt:
      name: "{{ items }}"
      state: latest
  vars:
      items:
      - unattended-upgrades


- name: Checking service
  command: sudo systemctl status "{{ item }}"
  with_items:
  # - firewalld
  # - ssh
  - unattended-upgrades
  register: result
  ignore_errors: yes
  

- name: showing report
  debug:
    var: result.stdout

- name: Remove Wireguard Repo
  ansible.builtin.apt_repository:
    repo: ppa:wireguard/wireguard
    state: absent


# - name: Add universe Wireguard Repo
#   ansible.builtin.apt_repository:
#     repo: universe

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

- name: Autoremove Packages
  apt:
    autoremove : yes
    purge : yes



  


