---
- name: Install some packages
  apt:
      name: "{{ items }}"
      state: latest
  vars:
      items:
      - filezilla
      - thunderbird
      - traceroute
      - flameshot
      - nmap
      - sssd
      - lightdm
      - firefox
      - vim
      - whois
      - curl
      - net-tools
      - openvpn
      - network-manager-openvpn
      - network-manager-openvpn-gnome
      - vlc
      - htop
      - dirmngr
      - gnupg
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - lm-sensors
    
- name: Download Google Chrome
  shell: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P /tmp
  
- name: Install Google Chrome
  shell: sudo apt install /tmp/./google-chrome-stable_current_amd64.deb -y

- name: Download Slack
  shell: wget https://downloads.slack-edge.com/releases/linux/4.20.0/prod/x64/slack-desktop-4.20.0-amd64.deb -P /tmp

- name: Install Slack
  shell: sudo apt install /tmp/./slack-desktop-4.20.0-amd64.deb -y


- name: Download TeamViewer
  shell: wget http://192.168.8.54/linux/teamviewer_amd64.deb -P /tmp

- name: Install TeamViewer
  shell: sudo apt install /tmp/./teamviewer_amd64.deb -y

- name: Auto remove 
  shell: sudo apt-get autoremove -y

- name: Download zoiper
  get_url:
    url: http://192.168.8.54/linux/Zoiper_3.3_Linux_Free_32Bit_64Bit.tar.gz
    dest: "{{ home_host }}"

- name: Extract zoiper files
  unarchive:
    src: "{{ home_host }}/Zoiper_3.3_Linux_Free_32Bit_64Bit.tar.gz"
    dest: "{{ home_host }}"
    remote_src: yes
    
- name: install zoiper
  expect:
    command: "./Zoiper_3.3_Linux_Free_64Bit.run"
    responses: 
      'Press \[Enter\] to continue :': "\n"
      'Do you accept this license\? \[y\/n\]:': "y"
      'Add Desktop Shortcut \[Y\/n\] :': "Y"
      'Is the selection above correct\? \[Y\/n\]:': "Y"
      'Installation Directory \[\/usr\/share\/Zoiper\]:': "\/usr\/share\/Zoiper"
      'Do you want to continue\? \[Y\/n\]:': "Y"
      'Launch Zoiper  \[Y\/n\]:': "Y"
    chdir: "{{ home_host }}"
    echo: yes

#==========Install dbeaver==============
- name: Install openjdk-8
  apt:
    name: openjdk-8-jdk

- name: Download dbeaver
  shell: wget https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb -P /tmp

- name: Install the repository package dbeaver
  shell: sudo apt install /tmp/./dbeaver-ce_latest_amd64.deb  -y

- name: Fix Packages Autoremove
  shell: sudo apt autoremove  -y
    
- name: Add apt key Sublime
  shell: curl -fsSL https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -

- name: Add the repository to source list
  shell: sudo add-apt-repository "deb https://download.sublimetext.com/ apt/stable/"

- name: Install sublime-text
  apt: 
    name: sublime-text
    update-cache: yes

- name: Add AG Projects Signing Key
  shell: curl -o /etc/apt/trusted.gpg.d/agp-debian-key.gpg http://download.ag-projects.com/agp-debian-key.gpg

- name: Add AG Blink Repository
  shell: echo "deb http://ag-projects.com/ubuntu focal main" | sudo tee -a /etc/apt/sources.list && echo "deb-src http://ag-projects.com/ubuntu focal main" | sudo tee -a /etc/apt/sources.list

- name: Update Packages repository
  shell: apt update -y
  
- name: Install Blink APP
  shell: apt install blink -y
